# This is a basic workflow to help you get started with Actions

name: livecd_builder

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 3 * * 1'
    - cron: '0 0 2 * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build livecd
    # The type of runner that the job will run on
    if: {{ github.event_name == 'push' && !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        ref: master

    # Runs a single command using the runners shell
    - name: Run makelivecd script
      shell: bash
      run: sudo bash makelivecd.sh

    # Runs a set of commands using the runners shell
    # upload files
    - name: Upload files
      env:
        RSYNC_HOST: ${{ secrets.HOST }}
        RSYNC_PATH: ${{ secrets.PATH }}
        KNOWN_HOST: ${{ secrets.KNOWN_HOST }}
        SSHPRIVKEY: ${{ secrets.KEY }}
      shell: bash
      run: |
        sudo apt update -qq
        sudo apt install -y tree rsync openssh-client
        cd root.x86_64/livecd/archlive
        sudo chown -R $UID upload
        sudo chown $UID .
        tree -a upload || true
        echo "Setting up KNOWN_HOST..."
        echo "$KNOWN_HOST" > kh
        echo "Setting up PRIV_KEY  ..."
        echo "$SSHPRIVKEY" |base64 -d > key
        chmod 0600 key
        echo "ASSERTING            ..."
        [ -n "$RSYNC_HOST" ] || (echo RSYNC_HOST is not set; exit 1)
        [ -n "$RSYNC_PATH" ] || (echo RSYNC_PATH is not set; exit 1)
        [ -n "$KNOWN_HOST" ] || (echo KNOWN_HOST is not set; exit 1)
        [ -n "$SSHPRIVKEY" ] || (echo SSHPRIVKEY is not set; exit 1)
        echo "Starting Upload      ..."
        rsync --delete -rlvPh -e "ssh -l ${RSYNC_HOST%@*} -i key -o StrictHostKeyChecking=ask -o UserKnownHostsFile=kh" upload/ "${RSYNC_HOST#*@}:${RSYNC_PATH}" || (shred kh key; exit 1)
        shred kh key
